# Generated by Django 3.1 on 2021-04-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=0, upload_to='photo/'),
            preserve_default=False,
        ),
    ]
